### ISSUE TITLE
GNU License

### ISSUE THREAD

**Issue by ilyapoz** [alexandernst/yii2-device-detect#1]
Hi!
Was the choice of a more restrictive license than that of the original library a conscious decision or is it just negligence? Because I will not use/contribute to a GNU licensed extension, but would in case of MIT (like original library).

**Comment by alexandernst** [comment]
@ilyapoz That was indeed a negligence. Let me change the license :)
I'm actually not really good at licenses, so I can use a suggestion here. What is the less restrictive license? WTFPL ?

**Comment by ilyapoz** [comment]
WTFPL is one of the leeast restrictive :) In cases like these I would just stick with the original library. It's MIT licensed.

**Comment by alexandernst** [comment]
MIT is it then :)
