### ISSUE TITLE
isDesktop() not working correctly

### ISSUE THREAD

**Issue by lgXenos** [alexandernst/yii2-device-detect#6]
`
var_dump('Yii::$app->params["devicedetect"]', Yii::$app->params['devicedetect']);
var_dump('Yii::$app->devicedetect->isDesktop()', Yii::$app->devicedetect->isDesktop());
var_dump('Yii::$app->devicedetect->isMobile()', Yii::$app->devicedetect->isMobile());
var_dump('Yii::$app->devicedetect->isTablet()', Yii::$app->devicedetect->isTablet());
`
Out this:

> string 'Yii::$app->params["devicedetect"]' (length=33)
> array (size=3)
>   'isMobile' => boolean false
>   'isTablet' => boolean false
>   'isDesktop' => boolean true
> string 'Yii::$app->devicedetect->isDesktop()' (length=36)
> boolean false
> string 'Yii::$app->devicedetect->isMobile()' (length=35)
> boolean false
> string 'Yii::$app->devicedetect->isTablet()' (length=35)
> boolean false

**Comment by alexandernst** [comment]
This is weird. How are you testing this? What browser?

**Comment by lgXenos** [comment]
Browser Cromium  47.0.2526.73 Ubuntu 14.04 (64-bit)
or
Mozilla FireFox 43
or, or, or... :)

Array of component already have right datas.
But use magic method - return not correct answer.
Look:
var_dump(Yii::$app->params["devicedetect"]);
array (size=3)
'isMobile' => boolean false
'isTablet' => boolean false
'isDesktop' => boolean true
As you can see - in index isDesktop - we have true!

But some magic - and we lost it (

var_dump(Yii::$app->devicedetect->isDesktop());
boolean false

**Comment by alexandernst** [comment]
You can't call `isDesktop` because there is no such method.

```php
/*Detect a mobile device*/
\Yii::$app->devicedetect->isMobile();

/*Detect a tablet device*/
\Yii::$app->devicedetect->isTablet();

/*Check all available methods here: http://demo.mobiledetect.net/ */
```

```Check all available methods here: http://demo.mobiledetect.net/```  <---- you must check the methods that exist and use them.

**Comment by lgXenos** [comment]
:)
It should be

I do not care - mobile or tablet.
Important: desktop - or not.

**Comment by alexandernst** [comment]
Then use the variable I have provided: `Yii::$app->params["devicedetect"]["isDesktop"]`. 

`Yii::$app->devicedetect->isDesktop()` doesn't exist.

**Comment by lgXenos** [comment]
Ok
Thanx for help!
I'm understand
